default linux
timeout 30
menu title RK3562 Boot

label linux
  kernel /Image
  fdt /rk3562.dtb
  append earlycon=uart8250,mmio32,0xff210000 console=ttyS0,1500000n8 quiet nosplash fbcon=map:1 loglevel=0 systemd.show_status=false rd.systemd.show_status=false udev.log_priority=0 plymouth.ignore-serial-consoles vt.global_cursor_default=0 video=DSI-1:800x1280@60,rotate=90 rw root=PARTUUID=c0ffee11-2233-4455-6677-8899aabbccdd rootfstype=ext4 rootwait

label linux-debug
  kernel /Image
  fdt /rk3562.dtb
  append earlycon=uart8250,mmio32,0xff210000 console=ttyS0,1500000n8 console=tty1 video=DSI-1:800x1280@60,rotate=90 rw root=PARTUUID=c0ffee11-2233-4455-6677-8899aabbccdd rootfstype=ext4 rootwait

label linux-fallback
  kernel /Image
  fdt /rk3562-fallback.dtb
  append earlycon=uart8250,mmio32,0xff210000 console=ttyS0,1500000n8 quiet nosplash fbcon=map:1 loglevel=0 systemd.show_status=false rd.systemd.show_status=false udev.log_priority=0 plymouth.ignore-serial-consoles vt.global_cursor_default=0 video=DSI-1:800x1280@60,rotate=90 rw root=PARTUUID=c0ffee11-2233-4455-6677-8899aabbccdd rootfstype=ext4 rootwait

label linux-fallback-debug
  kernel /Image
  fdt /rk3562-fallback.dtb
  append earlycon=uart8250,mmio32,0xff210000 console=ttyS0,1500000n8 console=tty1 video=DSI-1:800x1280@60,rotate=90 rw root=PARTUUID=c0ffee11-2233-4455-6677-8899aabbccdd rootfstype=ext4 rootwait
